spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
#    Raspberry Pi
    url: jdbc:mysql://192.168.219.111:3306/intro?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    # Centos 7
#    url: jdbc:mysql://116.45.90.231:3306/intro?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: intro
    password: intro123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jmx:
     enabled: false
     default-domain: hongsoon.ga
      
    
#  jpa:
#    properties:
#      hibernate: null
#      dialect: rg.hibernate.dialect.MySQLDialect
#      id:
#        new_generator_mappings: false
#        format_sql: true
        
#logging:
#  level:
#    org: null
#    hibernate:
#      SQL: DEBUG
#      type:
#        descriptor: null
#        sql: null
#        BasicBinder: TRACE