spring:
  profiles: 
    active: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    enabled: false
    default-domain: ENC(n8rl4RLMonDvQsD2uRntzz4MiH9I3LEuW433yE3hjBA=)
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      
      
# mail stmp
  mail:
    host: ENC(R+qAsrOUevT+dv12GatJSnQyi0FTLVWv)
    port: 587
    username: ENC(jzrPZP1QCZWELsnnZZCmuSCn/Er32Be/Fpo+xZpSolY=)
    password: ENC(SsZqp/04NrReg97XU+CCPlMlPX7r+r7L)
    properties:
      mail:
        stmp:
          auth: true
          starttls: 
            enable: true
# 암호화
jasypt:
    encryptor:
      bean: jasyptStringEncrptor    
    
---
spring:
  profiles: local      
  datasource:
#    Centos7(내부접속IP)
#    url: ENC(BshfTxXPXUqDXGyxbz97uypmoN0ZB+Fl7WeW7JrY45XsC8gGWfEYL08hgsNCqXuPjSVrTxR11iADoyFuZFMH14aFJnTV41/yCcU4P3y1OZN62zY2ExLjx9jPskzxmSrY/xG5/y2m+32fvbrGXujZ7p5/+4cYvSeh)
    url: jdbc:log4jdbc:mysql://192.168.219.10:3306/intro?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: ENC(P8FxIq/nBrpD50wSQP73Bg==)
    password: ENC(jKjBxEYAHxrlu0MDvUq+DdVXKYvxBYs0)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    dbcp2:
      validation-query: select 1
      test-while-idle: true
      time-between-eviction-runs-millis: 7200000  
  file:
    upload-dir: C:/eGovFrameDev/git/PROJECT/intro_park/src/main/webapp/uploads/portfolio/    
---



# Raspberry Pi(운영환경)
spring:
  profiles: oper      
  datasource:
#    Raspberry Pi(외부접속IP)
    url: ENC(K2qWuXu3E68sya/e5wWEDADYzaQYb0OCPVPd0kzJ49BXS1PnDsjBaF9Bh1R843p5Z9yhgSCEr07+qNOX3Af/mIBF7/s4n+pbDduFbjvrqZzyp6284x/yCIGadHxGzNdN9AbAigcR2SuzvEveXJdYEUDaLO0GTkIRzCzimy9oYUg=)
    username: ENC(P8FxIq/nBrpD50wSQP73Bg==)
    password: ENC(jKjBxEYAHxrlu0MDvUq+DdVXKYvxBYs0)
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    dbcp2:
      validation-query: select 1
      test-while-idle: true
      time-between-eviction-runs-millis: 7200000      
  file:
    upload-dir: /home/tomcat8/tomcat8/webapps/intro_park/uploads/portfolio/
   
    
  
#    Raspberry Pi(내부접속IP)
#    url: ENC(YIe4/EMasYSltTrimDC1lzu6n+S4x8y/xQFQXnYNnsnsbXkCsUWhnhAKVpe7qLyKlDQYobaCm141SsKSTwc6cEt8ioxWmLJRaDxXFQH1WqpjjhnlkWEJx2ari4B9CmSR17sJ4DeaHNpunOt+yEuKJR0/Ctlpz1/tOBtU7W4Pr1A=)
  



#  jpa:
#    properties:
#      hibernate: null
#      dialect: rg.hibernate.dialect.MySQLDialect
#      id:
#        new_generator_mappings: false
#        format_sql: true
        
#logging:
#  level:
#    org: null
#    hibernate:
#      SQL: DEBUG
#      type:
#        descriptor: null
#        sql: null
#        BasicBinder: TRACE