---
spring:

      mvc:
          view:
               prefix: /WEB-INF/jsp/
               suffix: .jsp
      datasource:
            url: jdbc:mysql://192.168.219.10:3306/portfolio?useUnicode=true&charaterEncoding=utf-8&useSSL=false
#            url: jdbc:mysql://172.30.1.35:3306/portfolio?useUnicode=true&charaterEncoding=utf-8&useSSL=false
            username: portfolio
            password: portfolio123
            driver-class-name: com.mysql.cj.jdbc.Driver
      